package thesis.machine;

/**
 *
 * @author Daniel <dmilith> Dettlaff
 */
public interface ServerConfiguration {
  /**
  * the host to be used.
  * <br>If you want to run the client server examples on two
  computers,
  * enter the computer name of the one that you want to use as
  server.
  PDF by iText, generated by Doctor, courtesy of db4obje*/
  public String HOST = "127.0.0.1";
  /**
  * the database file to be used by the server.
  */
  public String DBFILE = "main.db4o";
  /**
  * the port to be used by the server.
  */
  public int PORT = 60708;
  /**
  * the user name for access control.
  */
  public String USER = "dmilith";
  /**
  * the pasword for access control.
  */
  public String PASS = "void";

}
